apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-demo-ingress-prd
spec:
  rules:
  - host: gitops-prd.demo.local
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: demo-service
            port:
              number: 80
      - path: /css/
        pathType: Prefix 
        backend:
          service:
            name: demo-service
            port:
              number: 80
      - path: /js/
        pathType: Prefix 
        backend:
          service:
            name: demo-service
            port:
              number: 80
---
apiVersion: v1
data:
  allow-backend-server-header: "true"
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration
